[project]
name = "uvi-project"
description = "Based interactive uv project init script"
version = "1.0.0"
readme = "README.md"
license = "GPL-3.0"
requires-python = ">=3.10"
repository = "https://github.com/darragh0/uvi-project"
authors = [{ name = "darragh0" }]
dependencies = ["rich>=13.9.4"]
